name: packer
"on":
  push:
    branches:
    - '**'


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}
    - name: Run `packer init`
      id: init
      run: packer init .
    - name: Run `packer fmt`
      id: fmt
      run: packer fmt -check .
    - name: Run `packer validate`
      id: validate
      run: packer validate -syntax-only .
    - name: Run `packer build`
      id: build
      run: packer build .
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
